/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'yetsu\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-home' : '&#x21;',
			'icon-newspaper' : '&#x22;',
			'icon-image' : '&#x23;',
			'icon-images' : '&#x24;',
			'icon-camera' : '&#x25;',
			'icon-music' : '&#x26;',
			'icon-headphones' : '&#x27;',
			'icon-play' : '&#x28;',
			'icon-camera-2' : '&#x29;',
			'icon-podcast' : '&#x2a;',
			'icon-connection' : '&#x2b;',
			'icon-book' : '&#x2c;',
			'icon-books' : '&#x2d;',
			'icon-profile' : '&#x2e;',
			'icon-file' : '&#x2f;',
			'icon-file-2' : '&#x30;',
			'icon-folder' : '&#x31;',
			'icon-folder-open' : '&#x32;',
			'icon-tag' : '&#x33;',
			'icon-tags' : '&#x34;',
			'icon-cart' : '&#x35;',
			'icon-cart-2' : '&#x36;',
			'icon-qrcode' : '&#x37;',
			'icon-credit' : '&#x38;',
			'icon-phone' : '&#x39;',
			'icon-address-book' : '&#x3a;',
			'icon-envelop' : '&#x3b;',
			'icon-location' : '&#x3c;',
			'icon-mobile' : '&#x3d;',
			'icon-laptop' : '&#x3e;',
			'icon-screen' : '&#x3f;',
			'icon-tablet' : '&#x40;',
			'icon-bubbles' : '&#x41;',
			'icon-users' : '&#x42;',
			'icon-user' : '&#x43;',
			'icon-user-2' : '&#x44;',
			'icon-expand' : '&#x45;',
			'icon-contract' : '&#x46;',
			'icon-zoom-in' : '&#x47;',
			'icon-zoom-out' : '&#x48;',
			'icon-spinner' : '&#x49;',
			'icon-spinner-2' : '&#x4a;',
			'icon-stats' : '&#x4b;',
			'icon-bars' : '&#x4c;',
			'icon-cog' : '&#x4d;',
			'icon-cogs' : '&#x4e;',
			'icon-rocket' : '&#x4f;',
			'icon-airplane' : '&#x50;',
			'icon-accessibility' : '&#x51;',
			'icon-briefcase' : '&#x52;',
			'icon-cloud' : '&#x53;',
			'icon-menu' : '&#x54;',
			'icon-list' : '&#x55;',
			'icon-globe' : '&#x56;',
			'icon-earth' : '&#x57;',
			'icon-cloud-download' : '&#x58;',
			'icon-cloud-upload' : '&#x59;',
			'icon-attachment' : '&#x5a;',
			'icon-star' : '&#x5b;',
			'icon-star-2' : '&#x5c;',
			'icon-heart' : '&#x5d;',
			'icon-heart-2' : '&#x5e;',
			'icon-thumbs-up' : '&#x5f;',
			'icon-thumbs-up-2' : '&#x60;',
			'icon-happy' : '&#x61;',
			'icon-happy-2' : '&#x62;',
			'icon-smiley' : '&#x63;',
			'icon-tongue' : '&#x64;',
			'icon-tongue-2' : '&#x65;',
			'icon-sad' : '&#x66;',
			'icon-sad-2' : '&#x67;',
			'icon-wink' : '&#x68;',
			'icon-wink-2' : '&#x69;',
			'icon-grin' : '&#x6a;',
			'icon-cool' : '&#x6b;',
			'icon-cool-2' : '&#x6c;',
			'icon-angry' : '&#x6d;',
			'icon-shocked' : '&#x6e;',
			'icon-shocked-2' : '&#x6f;',
			'icon-confused' : '&#x70;',
			'icon-confused-2' : '&#x71;',
			'icon-exit' : '&#x72;',
			'icon-enter' : '&#x73;',
			'icon-arrow-up' : '&#x74;',
			'icon-arrow-right' : '&#x75;',
			'icon-arrow-left' : '&#x76;',
			'icon-arrow-down' : '&#x77;',
			'icon-console' : '&#x78;',
			'icon-code' : '&#x79;',
			'icon-google-plus' : '&#x7a;',
			'icon-facebook' : '&#x7b;',
			'icon-twitter' : '&#x7c;',
			'icon-youtube' : '&#x7d;',
			'icon-github' : '&#x7e;',
			'icon-tumblr' : '&#xe000;',
			'icon-pinterest' : '&#xe001;',
			'icon-linkedin' : '&#xe002;',
			'icon-foursquare' : '&#xe003;',
			'icon-html5' : '&#xe004;',
			'icon-html5-2' : '&#xe005;',
			'icon-css3' : '&#xe006;',
			'icon-database' : '&#xe007;',
			'icon-monitor' : '&#xe008;',
			'icon-check-alt' : '&#xe009;',
			'icon-x-altx-alt' : '&#xe00a;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};